<a href="https://colab.research.google.com/github/Argh-Jain11032006/UCS420_Argh-Jain_1024160084/blob/main/ArghJain_1024160084_Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [17]:
arr = np.array([1, 2, 3, 4, 5])

# Add 2 to all elements
arr + 2                    # [3 4 5 6 7]

# Multiply all by 3
arr * 3                    # [3 6 9 12 15]

# Divide all by 2
arr / 2                    # [0.5 1. 1.5 2. 2.5]

array([0.5, 1. , 1.5, 2. , 2.5])

In [18]:
arr = np.array([1, 2, 3, 6, 4, 5])

# Method 1: Slicing (fastest)
arr[::-1]                  # [5 4 6 3 2 1]

# Method 2: np.flip()
np.flip(arr)               # [5 4 6 3 2 1]

# Method 3: np.flipud()
np.flipud(arr)             # [5 4 6 3 2 1]

array([5, 4, 6, 3, 2, 1])

In [19]:
x = np.array([1,2,3,4,5,1,2,1,1,1])

# Get unique values and counts
unique_vals, counts = np.unique(x, return_counts=True)
# unique_vals: [1 2 3 4 5]
# counts:      [5 2 1 1 1]

# Find most frequent
most_freq = unique_vals[np.argmax(counts)]    # 1

# Get all indices
indices = np.where(x == most_freq)[0]         # [0 5 7 8 9]


In [20]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 15, 20, 35]])  # Shape: (3, 4)

# Statistics
np.mean(arr)               # 43.33
np.median(arr)             # 37.5
np.max(arr)                # 90
np.min(arr)                # 10
np.unique(arr)             # [10 15 20 30 35 40 50 60 70 80 90]

# Reshape: 3×4 → 4×3
reshaped = arr.reshape(4, 3)   # Shape: (4, 3)
# Same data, different layout

# Resize: 3×4 → 2×3
resized = np.resize(arr, (2, 3))  # Shape: (2, 3)
# Truncates to first 6 elements

In [21]:
arr = np.linspace(10, 100, 25)

# Properties
arr.ndim          # 1
arr.shape         # (25,)
arr.size          # 25
arr.dtype         # dtype('float64')
arr.nbytes        # 200 (25 elements × 8 bytes each)

# Transpose with reshape()
arr.reshape(-1, 1)         # Shape: (25, 1) - Column vector
arr.reshape(1, -1)         # Shape: (1, 25) - Row vector

# T attribute
arr.T              # No effect on 1D (still shape (25,))
arr.reshape(1,-1).T        # True transpose: (1,25) → (25,1)

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [22]:
import numpy as np

# Q.1: Basic operations
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1 + 2)    # [3 4 5 6 7]
print(arr1 * 3)    # [3 6 9 12 15]
print(arr1 / 2)    # [0.5 1. 1.5 2. 2.5]

# Q.2a: Reverse
arr2a = np.array([1, 2, 3, 6, 4, 5])
print(arr2a[::-1]) # [5 4 6 3 2 1]

# Q.2b: Most frequent
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique, counts = np.unique(x, return_counts=True)
most = unique[np.argmax(counts)]  # 1
idx = np.where(x == most)[0]       # [0 5 7 8 9]

# Q.3: 2D indexing
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr3[0, 1])  # 20
print(arr3[2, 0])  # 70

# Q.4: linspace analysis
arr4 = np.linspace(10, 100, 25)
print(arr4.shape)      # (25,)
print(arr4.nbytes)     # 200
print(arr4.reshape(-1, 1).shape)  # (25, 1)

# Q.5: 2D statistics
arr5 = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(f"Mean: {np.mean(arr5):.2f}")      # 43.33
print(f"Median: {np.median(arr5):.2f}")  # 37.50
print(f"Max: {np.max(arr5)}")            # 90
print(f"Min: {np.min(arr5)}")            # 10
print(arr5.reshape(4, 3))                # Reshape
print(np.resize(arr5, (2, 3)))           # Resize

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]
[5 4 6 3 2 1]
20
70
(25,)
200
(25, 1)
Mean: 43.33
Median: 37.50
Max: 90
Min: 10
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
